### ISSUE TITLE
Images with higher DPI show smaller

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#13]
I've noticed some images are showing at around 3/4 the size on-screen than Preview.app or Finder Quicklook and some other image viewers.

Using 'sips -g all <filename>' and comparing two files that display differently, I noticed:

This one shows smaller in MoliView than in Preview:

>  pixelWidth: 1199
>  pixelHeight: 770
>  dpiWidth: 96.000
>  dpiHeight: 96.000

vs ... this one show the same size in both MoliView & Preview/Quicklook

>  pixelWidth: 4957
>  pixelHeight: 3305
>  dpiWidth: 72.000
>  dpiHeight: 72.000

I think I've seen in another image app (but can't recall which) a setting like 'show images at retina resolution' or something ... which let you choose between letting each image pixel map to a screen pixel or present at effective size, respecting the DPI.

**Comment by phaibin** [comment]
Yes, I did it on purpose. Please check out this image:
![QQ20240824-161601](https://github.com/user-attachments/assets/687bbd2b-0080-4de7-aa48-82d0e6c59973)

From left to right: MoliView, Preview, Finder Quicklook, Xee.

This image is a screenshot made by another app. The original image size is just like the first. Images on iPhone will have a scale of 2 or 3 rather than 1 because of the retina display. Images on Mac have the same problem.

Xee always shows images in pixel sizes. Which leads to the image isn't very clear. Preview and Quicklook will consider the scale of the image. I don't know how Preview calculates the scale. I calculate the scale by my method. Which may be different from the one calculated by Preview. But anyway, it's better than always using the pixel size. If the scale is not 1, it will show in the status bar next to the image size.

Here's the image to demonstrate:
<img width="263" alt="QQ20220601-171219@2x" src="https://github.com/user-attachments/assets/d8ac18f5-e3aa-419d-9d68-6f7049506e10">

**Comment by mcackay** [comment]
Fair enough -- I guess I had just gotten used to Xee's representation :)

**Comment by phaibin** [comment]
Since many images are not shown properly I will turn off this feature until I find a proper way to deal with this.
