### ISSUE TITLE
Random browsing should support going back. - Mark

### ISSUE THREAD

**Issue by phaibin** [phaibin/MoliView#3]

**Comment by phaibin** [comment]
Wait for Mark's reply.

**Comment by mcackay** [comment]
> I made an experiment in Xee. If I randomly browse in a 15 images folder, the index will be: 1, 3, 13, 2, 12, 15, 14, 6, 11, 7, 10, 9, 8, 5, 4, 1, 3, 13... I think Xee is just rearranging the group and you will get the same index for the next loop. So that's why you can reverse back. If that's OK with you, I will make the change.

I think I follow what you're meaning. Whatever makes sense for your implementation of random :)

Thinking ahead, and considering subfolder support, Xee did support random browsing across the full index of files. So I suspect they had a cached file list they built up (and updated if you deleted, or added a file to the directory) which they then used as the jump index. Not sure.  Though perhaps that's taking things a bit far :)

**Comment by phaibin** [comment]
I think I've only used ten percent of Xee. Xee did a really good job. Maybe the best way is just to copy Xee as much as I can.😁 I'll write test code first to see if subfolder is workable.

**Comment by phaibin** [comment]
I've changed the strategy to be the same as Xee. So you can go back for random browsing now.

**Comment by mcackay** [comment]
> I think I've only used ten percent of Xee. Xee did a really good job. Maybe the best way is just to copy Xee as much as I can.😁 I'll write test code first to see if subfolder is workable.

> I've changed the strategy to be the same as Xee. So you can go back for random browsing now.

Sounds perfect to me. I approached the Xee devs (or new owners) several times, asking if they were going to update, or even were willing to share the source code publicly or privately so could be recompiled and bugs fixed, but alas.

--

Having a Product Owner background, I would advise getting clear on your vision for MoliView though. 

It's very easy to get caught up implementing features that have very limited utilisation, or introduce greater code complexity. I'd obviously love to see a modern 'Xee' app -- but in hunting for a replacement, I tried a bunch of others, which were 'image viewers or imager library browsers': Some became to 'fat' and were focussed on more browsing a gallery of thumbnails and library management, and because less useful as a 'advanced image viewer'. Some just had minor shortfalls, but didn't have developers that were as responsive as you (thanks!).  

But yeah -- just advising be intentional, or solicit some feedback from your users to help be sure that a feature is desirable.

**Comment by phaibin** [comment]
The way of image browsing in Xee is the core value of Xee. I can't find any other app that can do this so handy just like Xee.

First, MoliView was developed to satisfy myself. I want it to be dedicated to very few core functions. The functions in 1.4.0 are just all that I want.

But now I realize that people are so different. Since I published this app, I'd have to satisfy other people. Such as shortcuts, everyone has their own favorites.

And thank you for your good advices. I'd be cautious to add any new features.
